baseURL = "https://sathjana.foundation/"
languageCode = "en-us"
title = "Sathjana Foundation"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/Logo_word_English.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/Logo_word_English.svg"
    desktop_height = "200px"
    desktop_width = "5000px"
    alt = "Sathjana Foundation"

  [params.homepage_meta_tags]
    meta_description = "sathjanasathjanasathjanasathjanasathjanasathjanasathjanasathjanasathjana"
    meta_og_title = "sathjana"
    meta_og_type = "website"
    meta_og_url = "https://sathjana.foundation"
    meta_og_image = "https://sathjana.foundation"
    meta_og_description = "sathjanasathjanasathjanasathjanasathjanasathjana "
    meta_twitter_card = "summary"
    meta_twitter_site = "@sathjana"
    meta_twitter_creator = "@sathjana"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[[menu.main]]
	  name = "Join"
	  url = "/membership/"
    weight = 2

[[menu.main]]
    name = "Projects"
    url = "/work/"
    weight = 3

[[menu.main]]
    name = "Team"
    url = "/team/"
    weight = 4

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
